### PR TITLE
Add proposal for nodejs conventions

### PR DESCRIPTION
**Pull request by hpurmann**
These are some proposals and all up for discussion. We are mostly following these in [rplan-planning-objects](https://github.com/actano/rplan-planning-objects) already.

### CODE REVIEW

**Comment by pithu** [comment]
Great, i like the proposal except for one point:

The target `yarn test:unit` is misleading, i would expect unit tests here, but what at least in rplan-planning-objects these tests are integration tests, because there are testing against the neo4j. We should find a better name. integration ?

**Comment by hpurmann** [comment]
> The target `yarn test:unit` is misleading, i would expect unit tests here, but at least in rplan-planning-objects module these tests are integration tests, because there are testing against the neo4j. We should find a better name. integration ?

The target is meant for unit tests which should not require an external service running. That's why there is no such target in `rplan-planning-objects`. Still the convention would be valid, wouldn't it?

Are you proposing to add another convention to use `test:integration` for tests which need an external service (e.g. a database)?

**Comment by hpurmann** [comment]
Any more comments? I'd like to merge on Thursday if there are no objections.

**Comment by pithu** [comment]
> Are you proposing to add another convention to use `test:integration` for tests which need an external service (e.g. a database)?

How would we call out tests that are not testing the `rest-api` but testing the services together with a database, like we do in planning-object ? We cant name it `test:unit`, `test:rest-api` do not fit as well. i don't want to over engineer things, but the only thing that is coming to my mind is `test:integration`

**Comment by MerzDaniel** [comment]
* I vote against having a convention for using yarn. Workspaces was the only feature we really used in the monolith. The decision npm vs yarn should be up to the team that writes the service
See: https://iamturns.com/yarn-vs-npm-2018/
* The `run build` command should be optional. If no babel is used it is not required

**Comment by hpurmann** [comment]
> * I vote against having a convention for using yarn. Workspaces was the only feature we really used in the monolith. The decision npm vs yarn should be up to the team that writes the service
>   See: https://iamturns.com/yarn-vs-npm-2018/

From your linked article I see people commenting that npm still has consistency problems. Their lock file seem to change without the user explicitly upgrading to another version. Workspaces were not a reason to switch to yarn back then. It mainly was consistency, speed and the local cache.

Still, I have no strong opinion on making it a convention. For simplicity, I think it's easier if we stick with `yarn` for all services but I'm also fine with the service owners deciding on their own. Maybe other people have opinions too?

> * The `run build` command should be optional. If no babel is used it is not required

Yep, you are right. However, I don't see a case where babel would not be used. We agreed to write modern JS some time ago.

**Comment by pithu** [comment]
I agree with @hpurmann. When switching between js repos, it is very convenient and helpful when you can use the same tooling, same commands and find the same modern JS code.

**Pull request merged**
